
import React, { useState, useEffect, useMemo, useRef } from 'react';
import { TrendingUp, BarChart, ShoppingBag, Activity, CreditCard, Target, ArrowUp, ArrowDown, Zap, Sparkles, Bot as BotIcon, ChevronRight, Calendar, Filter, AlertTriangle, ShieldAlert, PackageSearch, Rocket, Coins, Flame, Headset, CalendarX, DatabaseZap, Star, TrendingDown, MousePointerClick, Info, X } from 'lucide-react';
import { DB } from '../lib/db';
import { ProductSKU, Shop } from '../lib/types';
import { getSkuIdentifier } from '../lib/helpers';

type RangeType = '7d' | '30d' | 'custom';
type MetricKey = 'gmv' | 'ca' | 'spend' | 'roi';

interface MetricPoint {
    current: number;
    previous: number;
}

interface MetricGroup {
    total: MetricPoint;
    self: MetricPoint;
    pop: MetricPoint;
}

interface DailyRecord {
    date: string;
    self: number;
    pop: number;
    total: number;
}

interface Diagnosis {
    id: string;
    type: 'asset' | 'stock_severe' | 'stock_warning' | 'explosive' | 'ad_star' | 'ad_waste' | 'cs_alert' | 'data_gap' | 'high_potential' | 'roi_drop' | 'cpc_spike' | 'low_efficiency';
    title: string;
    desc: string;
    skuInfo?: string;
    details: Record<string, string | number>;
    severity: 'critical' | 'warning' | 'info' | 'success';
}

const FullReportModal = ({ isOpen, onClose, diagnoses }: { isOpen: boolean; onClose: () => void; diagnoses: Diagnosis[] }) => {
    if (!isOpen) return null;
    return (
        <div className="fixed inset-0 bg-navy/60 backdrop-blur-md z-[100] flex items-center justify-center p-6 animate-fadeIn">
            <div className="bg-white rounded-[40px] shadow-2xl w-full max-w-5xl max-h-[85vh] flex flex-col overflow-hidden border border-slate-200">
                <div className="p-8 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div>
                        <h2 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-3">
                            <DatabaseZap className="text-brand" size={28} /> 全链路战略诊断报告
                        </h2>
                        <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mt-1 ml-10">Detailed Decision Intelligence Summary</p>
                    </div>
                    <button onClick={onClose} className="w-12 h-12 rounded-2xl bg-white border border-slate-200 flex items-center justify-center text-slate-400 hover:text-slate-900 transition-all shadow-sm"><X size={24} /></button>
                </div>
                <div className="flex-1 overflow-y-auto p-8 space-y-6 no-scrollbar bg-slate-50/20">
                    {diagnoses.length === 0 ? (
                        <div className="py-32 text-center flex flex-col items-center">
                            <ShieldAlert size={64} className="text-slate-100 mb-4" />
                            <p className="text-slate-400 font-black tracking-widest uppercase">系统运行极其稳健，暂无风险或机会项。</p>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-10">
                            {diagnoses.map(d => <DiagnosisCard key={d.id} diagnosis={d} isFullMode />)}
                        </div>
                    )}
                </div>
                <div className="p-6 border-t border-slate-100 text-center bg-white shrink-0">
                    <p className="text-[9px] font-black text-slate-300 uppercase tracking-[0.3em]">Neural Decision Strategy Generated by Yunzhou AI Core</p>
                </div>
            </div>
        </div>
    );
};

export const DashboardView = ({ skus, shops, addToast }: { skus: ProductSKU[], shops: Shop[], addToast: any }) => {
    const [isLoading, setIsLoading] = useState(true);
    const [activeMetric, setActiveMetric] = useState<MetricKey>('gmv');
    const [rangeType, setRangeType] = useState<RangeType>('7d');
    const [isFullReportOpen, setIsFullReportOpen] = useState(false);
    const [customRange, setCustomRange] = useState({
        start: new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0],
        end: new Date().toISOString().split('T')[0]
    });
    
    const [data, setData] = useState<Record<MetricKey, MetricGroup>>({
        gmv: { total: {current: 0, previous: 0}, self: {current: 0, previous: 0}, pop: {current: 0, previous: 0} },
        ca: { total: {current: 0, previous: 0}, self: {current: 0, previous: 0}, pop: {current: 0, previous: 0} },
        spend: { total: {current: 0, previous: 0}, self: {current: 0, previous: 0}, pop: {current: 0, previous: 0} },
        roi: { total: {current: 0, previous: 0}, self: {current: 0, previous: 0}, pop: {current: 0, previous: 0} }
    });

    const [allTrends, setAllTrends] = useState<Record<MetricKey, DailyRecord[]>>({
        gmv: [], ca: [], spend: [], roi: []
    });

    const [diagnoses, setDiagnoses] = useState<Diagnosis[]>([]);

    const enabledSkusMap = useMemo(() => {
        const map = new Map<string, ProductSKU>();
        skus.forEach(s => { if (s.isStatisticsEnabled) map.set(s.code, s); });
        return map;
    }, [skus]);

    const shopIdToName = useMemo(() => new Map(shops.map(s => [s.id, s.name])), [shops]);
    const shopIdToMode = useMemo(() => new Map(shops.map(s => [s.id, s.mode])), [shops]);

    const isSelfOperated = (mode: string | undefined): boolean => {
        if (!mode) return true;
        return ['自营', '入仓', 'LBP', 'SOPL'].includes(mode);
    };

    useEffect(() => {
        const fetchData = async () => {
            setIsLoading(true);
            let start: string;
            let end: string;

            if (rangeType === '7d') {
                start = new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0];
                end = new Date().toISOString().split('T')[0];
            } else if (rangeType === '30d') {
                start = new Date(Date.now() - 29 * 86400000).toISOString().split('T')[0];
                end = new Date().toISOString().split('T')[0];
            } else {
                start = customRange.start;
                end = customRange.end;
            }

            const startDateObj = new Date(start);
            const endDateObj = new Date(end);
            const diffDays = Math.ceil(Math.abs(endDateObj.getTime() - startDateObj.getTime()) / (1000 * 60 * 60 * 24)) + 1;
            
            const prevEndObj = new Date(startDateObj);
            prevEndObj.setDate(prevEndObj.getDate() - 1);
            const prevStartObj = new Date(prevEndObj);
            prevStartObj.setDate(prevStartObj.getDate() - (diffDays - 1));

            const now = new Date();
            const firstDayOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
            const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];

            try {
                const [currSz, currJzt, prevSz, prevJzt, monthSz, monthJzt] = await Promise.all([
                    DB.getRange('fact_shangzhi', start, end),
                    DB.getRange('fact_jingzhuntong', start, end),
                    DB.getRange('fact_shangzhi', prevStartObj.toISOString().split('T')[0], prevEndObj.toISOString().split('T')[0]),
                    DB.getRange('fact_jingzhuntong', prevStartObj.toISOString().split('T')[0], prevEndObj.toISOString().split('T')[0]),
                    DB.getRange('fact_shangzhi', firstDayOfMonth, yesterdayStr),
                    DB.getRange('fact_jingzhuntong', firstDayOfMonth, yesterdayStr)
                ]);

                const calculateStats = (sz: any[], jzt: any[]) => {
                    const stats = { gmv: { total: 0, self: 0, pop: 0 }, ca: { total: 0, self: 0, pop: 0 }, spend: { total: 0, self: 0, pop: 0 } };
                    sz.forEach(row => {
                        const code = getSkuIdentifier(row);
                        if (code && enabledSkusMap.has(code)) {
                            const amount = Number(row.paid_amount) || 0;
                            const items = Number(row.paid_items) || 0;
                            const skuAsset = enabledSkusMap.get(code);
                            const mode = shopIdToMode.get(skuAsset?.shopId || '') || '自营';
                            stats.gmv.total += amount; stats.ca.total += items;
                            if (isSelfOperated(mode)) { stats.gmv.self += amount; stats.ca.self += items; }
                            else { stats.gmv.pop += amount; stats.ca.pop += items; }
                        }
                    });
                    jzt.forEach(row => {
                        const code = getSkuIdentifier(row);
                        if (code && enabledSkusMap.has(code)) {
                            const cost = Number(row.cost) || 0;
                            const skuAsset = enabledSkusMap.get(code);
                            const mode = shopIdToMode.get(skuAsset?.shopId || '') || '自营';
                            stats.spend.total += cost;
                            if (isSelfOperated(mode)) stats.spend.self += cost; else stats.spend.pop += cost;
                        }
                    });
                    return stats;
                };

                const currentStats = calculateStats(currSz, currJzt);
                const previousStats = calculateStats(prevSz, prevJzt);
                
                const dailyAgg: Record<string, { gmv: any, ca: any, spend: any }> = {};
                for(let i=0; i<diffDays; i++) {
                    const d = new Date(startDateObj); d.setDate(d.getDate() + i);
                    const ds = d.toISOString().split('T')[0];
                    dailyAgg[ds] = { gmv: { self: 0, pop: 0 }, ca: { self: 0, pop: 0 }, spend: { self: 0, pop: 0 } };
                }
                currSz.forEach(r => {
                    const code = getSkuIdentifier(r);
                    if (code && enabledSkusMap.has(code) && dailyAgg[r.date]) {
                        const skuAsset = enabledSkusMap.get(code);
                        const mode = shopIdToMode.get(skuAsset?.shopId || '') || '自营';
                        if (isSelfOperated(mode)) { dailyAgg[r.date].gmv.self += Number(r.paid_amount) || 0; dailyAgg[r.date].ca.self += Number(r.paid_items) || 0; }
                        else { dailyAgg[r.date].gmv.pop += Number(r.paid_amount) || 0; dailyAgg[r.date].ca.pop += Number(r.paid_items) || 0; }
                    }
                });
                currJzt.forEach(r => {
                    const code = getSkuIdentifier(r);
                    if (code && enabledSkusMap.has(code) && dailyAgg[r.date]) {
                        const skuAsset = enabledSkusMap.get(code);
                        const mode = shopIdToMode.get(skuAsset?.shopId || '') || '自营';
                        if (isSelfOperated(mode)) dailyAgg[r.date].spend.self += Number(r.cost) || 0; else dailyAgg[r.date].spend.pop += Number(r.cost) || 0;
                    }
                });

                const sortedDates = Object.keys(dailyAgg).sort();
                const trends: Record<MetricKey, DailyRecord[]> = { gmv: [], ca: [], spend: [], roi: [] };
                sortedDates.forEach(date => {
                    const d = dailyAgg[date];
                    trends.gmv.push({ date, self: d.gmv.self, pop: d.gmv.pop, total: d.gmv.self + d.gmv.pop });
                    trends.ca.push({ date, self: d.ca.self, pop: d.ca.pop, total: d.ca.self + d.ca.pop });
                    trends.spend.push({ date, self: d.spend.self, pop: d.spend.pop, total: d.spend.self + d.spend.pop });
                    const tRoi = (d.spend.self + d.spend.pop) > 0 ? (d.gmv.self + d.gmv.pop) / (d.spend.self + d.spend.pop) : 0;
                    const selfRoi = d.spend.self > 0 ? d.gmv.self / d.spend.self : 0;
                    const popRoi = d.spend.pop > 0 ? d.gmv.pop / d.spend.pop : 0;
                    trends.roi.push({ date, self: selfRoi, pop: popRoi, total: tRoi });
                });

                setAllTrends(trends);
                setData({
                    gmv: { total: { current: currentStats.gmv.total, previous: previousStats.gmv.total }, self: { current: currentStats.gmv.self, previous: previousStats.gmv.self }, pop: { current: currentStats.gmv.pop, previous: previousStats.gmv.pop } },
                    ca: { total: { current: currentStats.ca.total, previous: previousStats.ca.total }, self: { current: currentStats.ca.self, previous: previousStats.ca.self }, pop: { current: currentStats.ca.pop, previous: previousStats.ca.pop } },
                    spend: { total: { current: currentStats.spend.total, previous: previousStats.spend.total }, self: { current: currentStats.spend.self, previous: previousStats.spend.self }, pop: { current: currentStats.spend.pop, previous: previousStats.spend.pop } },
                    roi: { 
                        total: { current: currentStats.spend.total > 0 ? currentStats.gmv.total / currentStats.spend.total : 0, previous: previousStats.spend.total > 0 ? currentStats.gmv.total / previousStats.spend.total : 0 },
                        self: { current: currentStats.spend.self > 0 ? currentStats.gmv.self / currentStats.spend.self : 0, previous: previousStats.spend.self > 0 ? currentStats.gmv.self / previousStats.spend.self : 0 },
                        pop: { current: currentStats.spend.pop > 0 ? currentStats.gmv.pop / currentStats.spend.pop : 0, previous: previousStats.spend.pop > 0 ? currentStats.gmv.pop / previousStats.spend.pop : 0 }
                    }
                });

                const newDiagnoses: Diagnosis[] = [];
                const skuGmvMap = new Map<string, number>();
                currSz.forEach(r => { const c = getSkuIdentifier(r); if(c) skuGmvMap.set(c, (skuGmvMap.get(c) || 0) + (Number(r.paid_amount) || 0)); });
                const skuCostMap = new Map<string, number>();
                currJzt.forEach(r => { const c = getSkuIdentifier(r); if(c) skuCostMap.set(c, (skuCostMap.get(c) || 0) + (Number(r.cost) || 0)); });

                const knownSkuCodes = new Set(skus.map(s => s.code));
                
                // 物理层新增资产逻辑（增量探测）：
                // 1. SKU 属于当前选定周期（如 1.26 导入的数据中包含）
                // 2. 且该 SKU 在资产库中从未登记
                // 3. 且该 SKU 在上一相邻周期（如 1.25）的物理表中也完全不存在
                const currActiveCodes = new Set(currSz.map(r => getSkuIdentifier(r)).filter(Boolean));
                const prevActiveCodes = new Set(prevSz.map(r => getSkuIdentifier(r)).filter(Boolean));
                
                currActiveCodes.forEach(code => {
                    if (code && !knownSkuCodes.has(code) && !prevActiveCodes.has(code)) {
                        const physRow = currSz.find(r => getSkuIdentifier(r) === code);
                        const physName = physRow?.product_name || '物理表商品名未知';
                        const physShop = physRow?.shop_name || '物理表店铺名未知';

                        newDiagnoses.push({ 
                            id: `asset-${code}`, 
                            type: 'asset', 
                            severity: 'critical', 
                            title: '物理层新增资产预警', 
                            desc: `探测到物理表出现全新活跃 SKU，但资产库未登记。`, 
                            skuInfo: `SKU [${code}] · ${physShop} · ${physName}`, 
                            details: { '发现时间': start, '建议': '前往资产名录补录以对齐统计' } 
                        });
                    }
                });

                const szDates = new Set(monthSz.map(r => r.date));
                const missingSz: string[] = [];
                let checkDate = new Date(firstDayOfMonth);
                const limitDate = new Date(yesterdayStr);
                while(checkDate <= limitDate) {
                    const dStr = checkDate.toISOString().split('T')[0];
                    if (!szDates.has(dStr)) missingSz.push(dStr);
                    checkDate.setDate(checkDate.getDate() + 1);
                }
                if (missingSz.length > 0) newDiagnoses.push({ id: 'gap-sz', type: 'data_gap', severity: 'warning', title: '数据流断层', desc: `本月探测到 ${missingSz.length} 个自然日销售记录缺失。`, details: { '最新断点': missingSz.slice(-1)[0] } });

                const getRichSkuStr = (code: string) => {
                    const sku = skus.find(s => s.code === code);
                    if (!sku) return `SKU [${code}]`;
                    const shopName = shopIdToName.get(sku.shopId) || '未知店铺';
                    return `SKU [${code}] · ${shopName} · ${sku.model || '未注型号'} · ${sku.configuration || '标准配置'}`;
                };

                skuGmvMap.forEach((gmv, code) => {
                    const cost = skuCostMap.get(code) || 0;
                    const roi = cost > 0 ? gmv / cost : 0;
                    const row = currSz.find(r => getSkuIdentifier(r) === code);
                    const cvr = Number(row?.paid_conversion_rate) || 0;
                    if (roi > 8 && gmv > 3000) {
                         newDiagnoses.push({ id: `exp-${code}`, type: 'explosive', severity: 'success', title: '爆款爆发预警', desc: `当前处于高投产红利期，建议追加预算。`, skuInfo: getRichSkuStr(code), details: { '当前ROI': roi.toFixed(1) } });
                    } else if (cvr > 0.12 && gmv > 500) {
                         newDiagnoses.push({ id: `pot-${code}`, type: 'high_potential', severity: 'info', title: '高转化潜力识别', desc: `转化率表现极佳，建议开启广告放大流量。`, skuInfo: getRichSkuStr(code), details: { '转化率': `${(cvr*100).toFixed(1)}%` } });
                    }
                });

                setDiagnoses(newDiagnoses.sort((a,b) => {
                    const order = { critical: 0, warning: 1, info: 2, success: 3 };
                    return order[a.severity] - order[b.severity];
                }));

            } catch (e) { console.error(e); }
            finally { setTimeout(() => setIsLoading(false), 300); }
        };
        fetchData();
    }, [rangeType, customRange, enabledSkusMap, shopIdToMode, shops, skus]);

    return (
        <div className="p-8 md:p-10 w-full animate-fadeIn space-y-10">
            <FullReportModal isOpen={isFullReportOpen} onClose={() => setIsFullReportOpen(false)} diagnoses={diagnoses} />
            
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-slate-200 pb-8">
                <div>
                    <div className="flex items-center gap-3 mb-2">
                        <div className="w-2 h-2 rounded-full bg-brand animate-pulse"></div>
                        <span className="text-[10px] font-black text-brand uppercase tracking-widest leading-none">物理层数据穿透中</span>
                        {enabledSkusMap.size > 0 && (
                            <span className="bg-brand/10 text-brand px-2.5 py-1 rounded-full text-[9px] font-black uppercase flex items-center gap-1.5 shadow-sm font-sans">
                                <Filter size={10} /> 已锁定 {enabledSkusMap.size} 个统计 SKU
                            </span>
                        )}
                    </div>
                    <h1 className="text-3xl font-black text-slate-900 tracking-tight">战略指挥控制台</h1>
                    <p className="text-slate-500 font-medium text-xs mt-1 opacity-60 font-sans">Performance Intelligence Dashboard & AI Decision Hub</p>
                </div>
                
                <div className="flex flex-col md:flex-row items-center gap-4">
                    {rangeType === 'custom' && (
                        <div className="flex items-center gap-2 bg-white border border-slate-200 p-1.5 rounded-2xl shadow-sm animate-slideIn">
                            <input type="date" value={customRange.start} onChange={e => setCustomRange(p => ({...p, start: e.target.value}))} className="bg-transparent border-none text-[10px] font-black text-slate-700 px-2 outline-none" />
                            <span className="text-slate-300 font-bold">-</span>
                            <input type="date" value={customRange.end} onChange={e => setCustomRange(p => ({...p, end: e.target.value}))} className="bg-transparent border-none text-[10px] font-black text-slate-700 px-2 outline-none" />
                        </div>
                    )}
                    <div className="flex bg-slate-100 p-1.5 rounded-2xl shadow-inner border border-slate-200">
                        {[{id:'7d',l:'近 7 天'},{id:'30d',l:'近 30 天'},{id:'custom',l:'自定义'}].map(i => (
                            <button key={i.id} onClick={() => setRangeType(i.id as RangeType)} className={`px-6 py-2 rounded-xl text-xs font-black transition-all ${rangeType === i.id ? 'bg-white text-slate-900 shadow-lg' : 'text-slate-400 hover:text-slate-600'}`}>{i.l}</button>
                        ))}
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">
                <KPICard isActive={activeMetric === 'gmv'} onClick={() => setActiveMetric('gmv')} title="GMV" value={data.gmv} prefix="¥" icon={<ShoppingBag size={20}/>} color="text-brand" bg="bg-brand/5" isLoading={isLoading} />
                <KPICard isActive={activeMetric === 'ca'} onClick={() => setActiveMetric('ca')} title="CA" value={data.ca} icon={<Activity size={20}/>} color="text-blue-600" bg="bg-blue-50" isLoading={isLoading} />
                <KPICard isActive={activeMetric === 'spend'} onClick={() => setActiveMetric('spend')} title="广告消耗" value={data.spend} prefix="¥" icon={<CreditCard size={20}/>} isHigherBetter={false} color="text-amber-600" bg="bg-amber-50" isLoading={isLoading} />
                <KPICard isActive={activeMetric === 'roi'} onClick={() => setActiveMetric('roi')} title="ROI" value={data.roi} isFloat icon={<Target size={20}/>} color="text-purple-600" bg="bg-purple-50" isLoading={isLoading} />
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-12 gap-8">
                <div className="xl:col-span-8 bg-white rounded-[48px] p-10 border border-slate-100 shadow-sm min-h-[540px] flex flex-col group/chart">
                    <div className="flex items-center justify-between mb-12 shrink-0">
                        <div className="flex items-center gap-4">
                            <div className="w-14 h-14 rounded-3xl bg-slate-50 flex items-center justify-center text-brand border border-slate-100 transition-transform">
                                <TrendingUp size={28} />
                            </div>
                            <div>
                                <h3 className="text-xl font-black text-slate-800 tracking-tight">{activeMetric.toUpperCase()} 增长曲线流</h3>
                                <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mt-0.5 font-sans">Physical Performance Temporal Stream</p>
                            </div>
                        </div>
                        <div className="flex gap-8">
                            <div className="flex items-center gap-2.5"><div className="w-3.5 h-3.5 rounded-full bg-brand shadow-sm"></div><span className="text-[10px] font-black text-slate-500 uppercase font-sans">自营店铺</span></div>
                            <div className="flex items-center gap-2.5"><div className="w-3.5 h-3.5 rounded-full bg-blue-500 shadow-sm"></div><span className="text-[10px] font-black text-slate-500 uppercase font-sans">POP 店铺</span></div>
                        </div>
                    </div>
                    <div className="flex-1 relative">
                        {isLoading ? (
                            <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-300">
                                <Activity className="animate-pulse mb-3" size={32} />
                                <p className="text-[10px] font-black uppercase tracking-[0.2em] font-sans">Processing...</p>
                            </div>
                        ) : allTrends[activeMetric].length > 0 ? (
                            <TrendVisual data={allTrends[activeMetric]} isFloat={activeMetric === 'roi'} />
                        ) : (
                            <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-300 opacity-30">
                                <BarChart size={64} className="mb-4" strokeWidth={1} />
                                <p className="text-xs font-bold uppercase tracking-widest font-sans">暂无活跃数据流</p>
                            </div>
                        )}
                    </div>
                </div>

                <div className="xl:col-span-4 bg-navy rounded-[48px] p-10 text-white shadow-2xl flex flex-col relative overflow-hidden group/room h-[540px]">
                    <div className="absolute top-0 right-0 w-80 h-80 bg-brand/5 rounded-full blur-[100px] -translate-y-1/3 translate-x-1/3"></div>
                    <div className="flex items-center gap-4 mb-8 relative z-10">
                        <div className="w-14 h-14 rounded-3xl bg-brand flex items-center justify-center shadow-lg border border-white/10 transition-transform duration-500">
                            <BotIcon size={28} className="text-white" />
                        </div>
                        <div>
                            <h3 className="text-xl font-black tracking-tight flex items-center gap-2 font-sans">AI 战略诊断室 <Sparkles size={16} className="text-brand animate-pulse" /></h3>
                            <p className="text-[10px] text-slate-500 font-black uppercase tracking-widest font-sans">Neural Decision Hub</p>
                        </div>
                    </div>
                    
                    <div className="flex-1 relative z-10 overflow-hidden mb-8 h-[280px]">
                        {diagnoses.length === 0 ? (
                            <div className="h-full flex flex-col items-center justify-center bg-white/5 rounded-[32px] border border-white/5 p-8 text-center opacity-40">
                                <DatabaseZap size={48} className="text-slate-500 mb-6" />
                                <p className="text-xs font-bold text-slate-400 font-sans">物理层链路平稳，暂无风险</p>
                            </div>
                        ) : (
                            <div className={`space-y-4 ${diagnoses.length > 2 ? 'animate-diagScroll' : ''}`}>
                                {diagnoses.map((d) => (
                                    <div key={d.id} className="h-[140px] shrink-0">
                                        <DiagnosisCard diagnosis={d} />
                                    </div>
                                ))}
                                {diagnoses.length > 2 && diagnoses.slice(0, 2).map((d) => (
                                    <div key={`${d.id}-repeat`} className="h-[140px] shrink-0">
                                        <DiagnosisCard diagnosis={d} />
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>

                    <button 
                        onClick={() => setIsFullReportOpen(true)}
                        className="w-full relative z-10 py-5 bg-brand text-white rounded-[24px] font-black text-sm hover:bg-[#5da035] transition-all flex items-center justify-center gap-3 shadow-2xl shadow-brand/20 group/btn active:scale-95 font-sans">
                        查看完整诊断报告 <ChevronRight size={16} className="group-hover/btn:translate-x-1 transition-transform" />
                    </button>
                </div>
            </div>

            <style>{`
                @keyframes diagScroll {
                    0% { transform: translateY(0); }
                    100% { transform: translateY(calc(-156px * ${diagnoses.length})); }
                }
                .animate-diagScroll {
                    animation: diagScroll ${Math.max(8, diagnoses.length * 4)}s linear infinite;
                }
                .animate-diagScroll:hover {
                    animation-play-state: paused;
                }
            `}</style>
        </div>
    );
};

const DiagnosisCard: React.FC<{ diagnosis: Diagnosis; isFullMode?: boolean }> = ({ diagnosis, isFullMode = false }) => {
    const configMap = {
        asset: { icon: <PackageSearch size={20}/>, color: "text-rose-500", bg: "bg-rose-500/10", border: "border-rose-500/20" },
        stock_severe: { icon: <ShieldAlert size={20}/>, color: "text-rose-500", bg: "bg-rose-500/10", border: "border-rose-500/20" },
        stock_warning: { icon: <AlertTriangle size={20}/>, color: "text-amber-500", bg: "bg-amber-500/10", border: "border-amber-500/20" },
        explosive: { icon: <Flame size={20}/>, color: "text-brand", bg: "bg-brand/10", border: "border-brand/20" },
        data_gap: { icon: <CalendarX size={20}/>, color: "text-amber-400", bg: "bg-amber-400/10", border: "border-amber-400/20" },
        high_potential: { icon: <Star size={20}/>, color: "text-blue-400", bg: "bg-blue-400/10", border: "border-blue-400/20" }
    };
    const cfg = configMap[diagnosis.type as keyof typeof configMap] || configMap.asset;
    
    if (isFullMode) {
        return (
            <div className={`rounded-[32px] border transition-all hover:bg-white/5 group/dcard ${cfg.bg} ${cfg.border} animate-slideIn p-8 h-full`}>
                <div className="flex gap-5 mb-6">
                    <div className={`${cfg.color} shrink-0 mt-0.5 group-hover/dcard:rotate-12 transition-transform duration-500`}>{cfg.icon}</div>
                    <div className="min-w-0">
                        <div className="flex items-center gap-3 mb-1">
                            <p className="text-lg font-black uppercase tracking-tight truncate">{diagnosis.title}</p>
                            {diagnosis.severity === 'critical' && <span className="bg-rose-500 text-white text-[8px] font-black px-1.5 py-0.5 rounded uppercase font-sans">Critical</span>}
                        </div>
                        <p className="text-xs text-slate-500 font-black mb-2 opacity-80">{diagnosis.skuInfo}</p>
                        <p className="text-sm text-slate-400 font-bold leading-relaxed">{diagnosis.desc}</p>
                    </div>
                </div>
                <div className="bg-white/40 rounded-2xl p-6 border border-white/20 space-y-3">
                    {Object.entries(diagnosis.details).map(([key, val]) => (
                        <div key={key} className="flex justify-between items-center text-xs">
                            <span className="text-slate-500 font-black uppercase tracking-widest font-sans">{key}</span>
                            <span className="text-slate-800 font-black tabular-nums">{val}</span>
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    return (
        <div className={`rounded-[32px] border transition-all hover:bg-white/5 group/dcard ${cfg.bg} ${cfg.border} animate-slideIn p-5 h-[140px] flex flex-col justify-center`}>
            <div className="flex items-center gap-3 mb-2">
                <div className={`${cfg.color} shrink-0 group-hover/dcard:scale-110 transition-transform`}>{cfg.icon}</div>
                <p className="text-sm font-black uppercase tracking-tight text-slate-100 truncate">{diagnosis.title}</p>
            </div>
            <div className="pl-8 space-y-1">
                <p className="text-[10px] text-slate-300 font-black truncate opacity-90">{diagnosis.skuInfo}</p>
                <p className="text-[11px] text-slate-400 font-bold leading-relaxed line-clamp-2 opacity-70">{diagnosis.desc}</p>
            </div>
        </div>
    );
};

const TrendVisual: React.FC<{ data: DailyRecord[]; isFloat?: boolean }> = ({ data, isFloat = false }) => {
    const [hoverIndex, setHoverIndex] = useState<number | null>(null);
    const containerRef = useRef<HTMLDivElement>(null);
    const width = 800; const height = 300; const padding = { top: 30, right: 30, bottom: 50, left: 30 };
    
    // 动态缩放逻辑：确保自营与POP的高度差异被精准体现
    const maxVal = Math.max(...data.map(d => Math.max(d.self, d.pop)), 0.1) * 1.2;
    
    const getX = (i: number) => padding.left + (i / (data.length - 1)) * (width - padding.left - padding.right);
    const getY = (v: number) => height - padding.bottom - (v / maxVal) * (height - padding.top - padding.bottom);
    const formatVal = (v: number) => isFloat ? v.toFixed(2) : Math.round(v).toLocaleString();

    const generateAreaPath = (points: number[]) => {
        if (points.length === 0) return "";
        let path = `M ${getX(0)},${height - padding.bottom}`;
        points.forEach((v, i) => { path += ` L ${getX(i)},${getY(v)}`; });
        path += ` L ${getX(points.length - 1)},${height - padding.bottom} Z`;
        return path;
    };

    return (
        <div ref={containerRef} className="w-full h-full relative cursor-crosshair group/trend font-sans" onMouseMove={(e) => { const rect = containerRef.current!.getBoundingClientRect(); const x = ((e.clientX - rect.left) / rect.width) * width; const idx = Math.round(((x - padding.left) / (width - padding.left - padding.right)) * (data.length - 1)); if(idx >= 0 && idx < data.length) setHoverIndex(idx); }} onMouseLeave={() => setHoverIndex(null)}>
            <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full">
                <defs>
                    <linearGradient id="gSelf" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#70AD47" stopOpacity="0.4"/><stop offset="100%" stopColor="#70AD47" stopOpacity="0"/></linearGradient>
                    <linearGradient id="gPop" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3B82F6" stopOpacity="0.4"/><stop offset="100%" stopColor="#3B82F6" stopOpacity="0"/></linearGradient>
                </defs>
                
                {/* 阴影填充层 */}
                <path d={generateAreaPath(data.map(d => d.self))} fill="url(#gSelf)" className="transition-all duration-500" />
                <path d={generateAreaPath(data.map(d => d.pop))} fill="url(#gPop)" className="transition-all duration-500" />
                
                {/* 曲线边框层 */}
                <path d={`M ${data.map((d,i) => `${getX(i)},${getY(d.self)}`).join(' L ')}`} fill="none" stroke="#70AD47" strokeWidth="3" strokeLinecap="round" className="transition-all duration-500" />
                <path d={`M ${data.map((d,i) => `${getX(i)},${getY(d.pop)}`).join(' L ')}`} fill="none" stroke="#3B82F6" strokeWidth="3" strokeLinecap="round" className="transition-all duration-500" />
                
                {hoverIndex !== null && (
                    <>
                        <line x1={getX(hoverIndex)} y1={padding.top} x2={getX(hoverIndex)} y2={height - padding.bottom} stroke="#020617" strokeDasharray="6 4" strokeWidth="1" />
                        <circle cx={getX(hoverIndex)} cy={getY(data[hoverIndex].self)} r="5" fill="#fff" stroke="#70AD47" strokeWidth="3" />
                        <circle cx={getX(hoverIndex)} cy={getY(data[hoverIndex].pop)} r="5" fill="#fff" stroke="#3B82F6" strokeWidth="3" />
                    </>
                )}
                <text x={padding.left} y={height - 15} fontSize="10" fill="#94a3b8" fontWeight="900" className="uppercase tracking-widest">{data[0].date.substring(5)}</text>
                <text x={width - padding.right} y={height - 15} textAnchor="end" fontSize="10" fill="#94a3b8" fontWeight="900" className="uppercase tracking-widest">{data[data.length-1].date.substring(5)}</text>
            </svg>
            
            {hoverIndex !== null && (
                <div className="absolute z-50 pointer-events-none bg-slate-900/95 backdrop-blur text-white rounded-2xl p-5 shadow-2xl animate-fadeIn font-sans" style={{ left: `${(getX(hoverIndex)/width)*100}%`, top: '40%', transform: `translate(${hoverIndex > data.length/2 ? '-110%' : '15%'}, -50%)` }}>
                    <p className="text-[10px] font-black text-slate-500 mb-3 border-b border-white/10 pb-2 uppercase tracking-widest">{data[hoverIndex].date}</p>
                    <div className="space-y-2">
                        <div className="flex justify-between gap-10 items-center"><span className="flex items-center gap-2 text-[10px] font-bold text-slate-300"><div className="w-1.5 h-1.5 rounded-full bg-brand"></div>自营店铺</span><span className="text-xs font-black tabular-nums">{formatVal(data[hoverIndex].self)}</span></div>
                        <div className="flex justify-between gap-10 items-center"><span className="flex items-center gap-2 text-[10px] font-bold text-slate-300"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div>POP 店铺</span><span className="text-xs font-black tabular-nums">{formatVal(data[hoverIndex].pop)}</span></div>
                        <div className="pt-2 border-t border-white/10 flex justify-between gap-10 items-center"><span className="text-[10px] font-black text-brand uppercase tracking-widest">当日合计</span><span className="text-sm font-black text-brand tabular-nums">{formatVal(data[hoverIndex].total)}</span></div>
                    </div>
                </div>
            )}
        </div>
    );
};

const KPICard = ({ title, value, prefix = "", isFloat = false, icon, isHigherBetter = true, color, bg, isLoading, isActive, onClick }: any) => {
    const calculateChange = (curr: number, prev: number) => prev === 0 ? (curr > 0 ? 100 : 0) : ((curr - prev) / prev) * 100;
    const formatVal = (v: number) => isFloat ? v.toFixed(2) : Math.round(v).toLocaleString();
    const totalChange = calculateChange(value.total.current, value.total.previous);
    const selfChange = calculateChange(value.self.current, value.self.previous);
    const popChange = calculateChange(value.pop.current, value.pop.previous);

    const renderChangeBadge = (change: number) => {
        const isPositive = change >= 0;
        const isGood = (isPositive && isHigherBetter) || (!isPositive && !isHigherBetter);
        const colorClass = isGood ? 'text-green-600 bg-green-50' : 'text-rose-600 bg-rose-50';
        return (
            <div className={`text-[9px] font-black px-1.5 py-0.5 rounded-md inline-flex items-center gap-0.5 ${colorClass} font-sans`}>
                {isPositive ? <ArrowUp size={8} strokeWidth={4} /> : <ArrowDown size={8} strokeWidth={4} />}
                {Math.abs(change).toFixed(1)}%
            </div>
        );
    };

    return (
        <button onClick={onClick} className={`bg-white rounded-[40px] border text-left transition-all duration-500 group flex flex-col overflow-hidden relative active:scale-95 ${isActive ? 'ring-[6px] ring-brand/10 border-brand shadow-2xl scale-[1.02]' : 'border-slate-100 shadow-sm hover:shadow-xl hover:border-slate-200'}`}>
            <div className="p-8 flex-1 space-y-6">
                <div className="flex justify-between items-start">
                    <div className={`w-14 h-14 ${bg} rounded-[22px] flex items-center justify-center ${color} group-hover:scale-110 transition-transform duration-700`}>{icon}</div>
                    <div className="text-right">
                        <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-1.5 font-sans">{title}</h3>
                        {!isLoading && (
                            <div className="flex items-center gap-1.5 justify-end">
                                {renderChangeBadge(totalChange)}
                                <span className="text-[8px] font-black text-slate-300 uppercase font-sans">环比</span>
                            </div>
                        )}
                    </div>
                </div>
                <div>{isLoading ? <div className="h-10 w-3/4 bg-slate-50 animate-pulse rounded-2xl"></div> : <p className="text-4xl font-black text-slate-900 tabular-nums tracking-tighter">{prefix}{formatVal(value.total.current)}</p>}</div>
            </div>
            <div className={`bg-slate-50/50 border-t p-5 grid grid-cols-2 gap-4 ${isActive ? 'bg-brand/5 border-brand/10' : 'border-slate-50'}`}>
                <div className="min-w-0">
                    <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1 font-sans">自营店铺</p>
                    <div className="flex items-center gap-1.5 min-w-0">
                        <p className="text-[11px] font-black text-slate-700 tabular-nums truncate">{prefix}{formatVal(value.self.current)}</p>
                        {!isLoading && renderChangeBadge(selfChange)}
                    </div>
                </div>
                <div className="border-l border-slate-200 pl-4 min-w-0">
                    <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1 font-sans">POP 店铺</p>
                    <div className="flex items-center gap-1.5 min-w-0">
                        <p className="text-[11px] font-black text-slate-700 tabular-nums truncate">{prefix}{formatVal(value.pop.current)}</p>
                        {!isLoading && renderChangeBadge(popChange)}
                    </div>
                </div>
            </div>
        </button>
    );
};
