
import { FieldDefinition } from './types';

export const INITIAL_SHANGZHI_SCHEMA: FieldDefinition[] = [
    { key: 'date', label: '日期', type: 'TIMESTAMP', required: true, tags: ['时间'] },
    { key: 'product_name', label: '商品名称', type: 'STRING', required: false },
    { key: 'sku_code', label: 'SKU', type: 'STRING', required: true, tags: ['SKU编码'] },
    { key: 'brand', label: '品牌', type: 'STRING', required: false },
    { key: 'category_l1', label: '一级类目', type: 'STRING', required: false },
    { key: 'category_l2', label: '二级类目', type: 'STRING', required: false },
    { key: 'category_l3', label: '三级类目', type: 'STRING', required: false },
    { key: 'shop_name', label: '店铺名称', type: 'STRING', required: false }, // 改为 false
    { key: 'business_mode', label: '经营模式', type: 'STRING', required: false },
    { key: 'pv', label: '浏览量', type: 'INTEGER', required: false },
    { key: 'uv', label: '访客数', type: 'INTEGER', required: false },
    { key: 'pv_per_uv', label: '人均浏览量', type: 'REAL', required: false },
    { key: 'avg_stay_duration', label: '平均停留时长', type: 'REAL', required: false },
    { key: 'paid_users', label: '成交人数', type: 'INTEGER', required: false },
    { key: 'paid_conversion_rate', label: '成交转化率', type: 'REAL', required: false },
    { key: 'paid_orders', label: '成交单量', type: 'INTEGER', required: false },
    { key: 'paid_items', label: 'CA', type: 'INTEGER', required: false, tags: ['成交商品件数'] },
    { key: 'paid_amount', label: 'GMV', type: 'REAL', required: true, tags: ['成交金额', 'GMV'] },
    { key: 'paid_aov', label: '成交客单价', type: 'REAL', required: false },
    { key: 'add_to_cart_users', label: '加购人数', type: 'INTEGER', required: false },
    { key: 'add_to_cart_conversion_rate', label: '加购转化率', type: 'REAL', required: false },
    { key: 'add_to_cart_items', label: '加购商品件数', type: 'INTEGER', required: false },
    { key: 'product_id', label: '商品ID', type: 'STRING', required: false },
    { key: 'item_number', label: '货号', type: 'STRING', required: false },
    { key: 'product_followers', label: '商品关注数', type: 'INTEGER', required: false },
    { key: 'paid_customers', label: '成交客户数', type: 'INTEGER', required: false },
    { key: 'uv_value', label: 'UV价值', type: 'REAL', required: false },
    { key: 'last_listed_at', label: '最近上架时间', type: 'TIMESTAMP', required: false },
    { key: 'pdp_bounce_rate', label: '详情页跳出率', type: 'REAL', required: false },
    { key: 'search_impressions', label: '搜索曝光量', type: 'INTEGER', required: false },
    { key: 'search_clicks', label: '搜索点击次数', type: 'INTEGER', required: false },
    { key: 'search_ctr', label: '搜索点击率', type: 'REAL', required: false },
    { key: 'predicted_sales_7d', label: '系统预测未来7天销量', type: 'INTEGER', required: false },
    { key: 'ordering_customers', label: '下单客户数', type: 'INTEGER', required: false },
    { key: 'ordering_items', label: '下单商品件数', type: 'INTEGER', required: false },
    { key: 'order_amount', label: '下单金额', type: 'REAL', required: false },
    { key: 'order_to_paid_conversion_rate', label: '下单成交转化率', type: 'REAL', required: false },
    { key: 'order_conversion_rate', label: '下单转化率', type: 'REAL', required: false },
    { key: 'pv_stock_rate', label: 'PV现货率', type: 'REAL', required: false },
    { key: 'aov', label: '客单价', type: 'REAL', required: false },
    { key: 'price_per_item', label: '件单价', type: 'REAL', required: false },
    { key: 'refund_amount', label: '取消及售后退款金额', type: 'REAL', required: false },
    { key: 'refund_items', label: '取消及售后退款件数', type: 'INTEGER', required: false },
    { key: 'refund_orders', label: '取消及售后退款单量', type: 'INTEGER', required: false }
];

export const INITIAL_JINGZHUNTONG_SCHEMA: FieldDefinition[] = [
    { key: 'date', label: '日期', type: 'TIMESTAMP', required: true, tags: ['时间'] },
    { key: 'account_nickname', label: '账户昵称', type: 'STRING', required: false, tags: ['账户'] },
    { key: 'tracked_sku_id', label: '跟单SKU ID', type: 'STRING', required: false },
    { key: 'tracked_sku_name', label: '跟单SKU名称', type: 'STRING', required: false },
    { key: 'impressions', label: '展现数', type: 'INTEGER', required: false, tags:['展现量'] },
    { key: 'clicks', label: '点击数', type: 'INTEGER', required: true, tags:['点击量'] },
    { key: 'ctr', label: '点击率(%)', type: 'REAL', required: false },
    { key: 'cost', label: '花费', type: 'REAL', required: true, tags:['消耗'] },
    { key: 'cpm', label: '千次展现成本', type: 'REAL', required: false },
    { key: 'cpc', label: '平均点击成本', type: 'REAL', required: false },
    { key: 'direct_orders', label: '直接订单行', type: 'INTEGER', required: false },
    { key: 'direct_order_amount', label: '直接订单金额', type: 'REAL', required: false },
    { key: 'indirect_orders', label: '间接订单行', type: 'INTEGER', required: false },
    { key: 'indirect_order_amount', label: '间接订单金额', type: 'REAL', required: false },
    { key: 'total_orders', label: '总订单行', type: 'INTEGER', required: false, tags: ['总下单单量'] },
    { key: 'total_order_amount', label: '总订单金额', type: 'REAL', required: false },
    { key: 'direct_add_to_cart', label: '直接加购数', type: 'INTEGER', required: false },
    { key: 'indirect_add_to_cart', label: '间接加购数', type: 'INTEGER', required: false },
    { key: 'total_add_to_cart', label: '总加购数', type: 'INTEGER', required: false },
    { key: 'conversion_rate', label: '转化率(%)', type: 'REAL', required: false },
    { key: 'cost_per_order', label: '平均订单成本', type: 'REAL', required: false },
    { key: 'roi', label: 'ROI', type: 'REAL', required: false, tags: ['投产比', '总ROI'] },
    { key: 'presale_orders', label: '预售订单行', type: 'INTEGER', required: false },
    { key: 'presale_order_amount', label: '预售订单金额', type: 'REAL', required: false }
];

export const INITIAL_CUSTOMER_SERVICE_SCHEMA: FieldDefinition[] = [
    { key: 'date', label: '日期', type: 'TIMESTAMP', required: true, tags: ['时间'] },
    { key: 'agent_account', label: '客服', type: 'STRING', required: true, tags: ['客服账号'] },
    { key: 'inquiries', label: '咨询量', type: 'INTEGER', required: false },
    { key: 'chats', label: '接待量', type: 'INTEGER', required: true },
    { key: 'no_response_count', label: '无响应量', type: 'INTEGER', required: false },
    { key: 'response_rate', label: '回复率', type: 'REAL', required: false },
    { key: 'response_rate_30s', label: '30s应答率', type: 'REAL', required: false },
    { key: 'satisfaction_rate', label: '满意率', type: 'REAL', required: false, tags: ['满意度'] },
    { key: 'review_invitation_rate', label: '邀评率', type: 'REAL', required: false },
    { key: 'avg_messages_per_chat', label: '平均回复消息数', type: 'REAL', required: false },
    { key: 'avg_chat_duration', label: '平均会话时长', type: 'REAL', required: false },
    { key: 'avg_first_response_time', label: '首次平均响应时间', type: 'REAL', required: false },
    { key: 'avg_response_time', label: '新平均响应时间', type: 'REAL', required: false, tags: ['平均响应时长'] },
    { key: 'message_assigned_count', label: '留言分配量', type: 'INTEGER', required: false },
    { key: 'message_handled_count', label: '留言接待量', type: 'INTEGER', required: false },
    { key: 'message_response_rate', label: '留言响应率', type: 'REAL', required: false },
    { key: 'resolution_rate', label: '解决率', type: 'REAL', required: false },
    { key: 'presale_chats_users', label: '售前接待人数', type: 'INTEGER', required: false },
    { key: 'converted_order_users', label: '促成下单人数', type: 'INTEGER', required: false },
    { key: 'converted_shipped_users', label: '促成出库人数', type: 'INTEGER', required: false },
    { key: 'converted_orders', label: '促成下单订单数', type: 'INTEGER', required: false },
    { key: 'converted_shipped_orders', label: '促成出库订单数', type: 'INTEGER', required: false },
    { key: 'converted_order_items', label: '促成下单商品数', type: 'INTEGER', required: false },
    { key: 'converted_shipped_items', label: '促成出库商品数', type: 'INTEGER', required: false },
    { key: 'converted_order_amount', label: '促成下单商品金额', type: 'REAL', required: false },
    { key: 'converted_shipped_amount', label: '促成出库商品金额', type: 'REAL', required: false }
];
